package com.rockpaperscissors.model.player;

import com.rockpaperscissors.model.game.MovementTypes;

/**
 * This is the interface which models the behavior of the player,
 * for now it only contains the method to perform the movement.
 * <p>
 * This interface should be sealed to prevent wrong classes to
 * inherit from this one in order to preserve the Liskov Principle.
 */
sealed public interface IPlayer permits FixedMovementPlayer, RandomMovementPlayer
{

    /**
     * This method is the one to use to generate a movement for this
     * player instance.
     *
     * @return The movement generated by the implementing class.
     */
    MovementTypes performMovement();
}
